import Head from 'next/head'
import { GitLabCorner } from '../components/GitHubCorner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='text-red'>111</div>
        <GitLabCorner href="https://github.com/RainyLiao/eslint-config" />
      </main>
    </>
  )
}
